#!/usr/bin/env python3
# Hey Emacs, this is -*-python-*-

# payson2pdf: translate a CSV report from Swish into PDFs

import sys
import os
import argparse
import csv
import re
from itertools import groupby

import fpdf

excel_escape_re = re.compile('^="(.*)"$')
numeric_re = re.compile('^-?\d+,\d\d$')


pdf_fields = {
    'sv': (('date', 'Datum:'),
           ('type', 'Typ:'),
           ('status', 'Status:'),
           ('payson ref.', 'Payson referens:'),
           ('reference', 'Egen referens:'),
           ('sender', 'Avsändare:'),
           ('receiver', 'Mottagare:'),
           ('description', 'Beskrivning:'),
           ('amount', 'Belopp:'),
           ('vat (articles)', 'Moms (artiklar):'),
           ('fee', 'Avgift:'),
           ('vat (fee)', 'Moms (avgift):'),
           ('change', 'Saldoändring:'),
           ('balance', 'Nytt saldo:'),
           ('currency', 'Valuta:'),
       )
}

parser = argparse.ArgumentParser(description = 'Translate Payson CSV report into PDFs')
parser.add_argument('-o', '--output-dir', default = '.',
                    help = 'Output directory for the files, default is current directory.')
parser.add_argument('-e', '--encoding', default = 'UTF-8',
                    help = 'Input file text encoding, default UTF-8.')
parser.add_argument('-r', '--replace', action = 'store_true',
                    help = 'Replace any existing PDF files.')
parser.add_argument('input_files', metavar = 'CSV', nargs = '*',
                    help = 'Files to process. If none are provided, stdin is read.')

def main():
    args = parser.parse_args()

    if args.input_files:
        input_files = [open(fname, mode = 'rt', newline = '', encoding = args.encoding)
                       for fname in args.input_files]
    else:
        input_files = [sys.stdin]

    for f in input_files:
        translate_csv(csv.reader(f, delimiter = ';', skipinitialspace = True), args)


def translate_csv(csv_input, args):
    def keyfunc(v):
        return v['_date_only']

    rows = sorted(read_csv(csv_input), key=keyfunc)
    for date, payments in groupby(rows, key=keyfunc):
        generate_pdf(date, payments, args)


def read_csv(csv_input):
    header = None
    for row in csv_input:
        if header is None:
            header = [h.lower() for h in row]
        else:
            values = {}
            for i, field in enumerate(header):
                if field:
                    values[field] = strip_escape(row[i])

            values['_date_only'] = values['date'].split()[0]
            yield values


def strip_escape(data):
    """Remove any ="xyz" Excel style escaping."""
    m = excel_escape_re.match(data)
    if m:
        return m.group(1)
    else:
        return data


def generate_pdf(date, payments, args, language = 'sv'):
    filename = 'payson_{}.pdf'.format(date)
    path = os.path.join(args.output_dir, filename)

    if os.path.exists(path) and not args.replace:
        #print('not replacing existing {}'.format(path))
        return

    payments = sorted(payments, key=lambda v: v['payson ref.'])

    gross_amount = sum_amounts(payments, 'amount')
    total_fee = sum_amounts(payments, 'fee')
    net_amount = sum_amounts(payments, 'change')
    balance = payments[-1]['balance']

    pdf = fpdf.FPDF('P', 'mm', 'A4')

    # Generate summary page for all payments this day
    pdf.add_page()
    pdf.set_font('Arial', 'B', 18)
    pdf.cell(0, 10, 'Paysonbetalningar', align= 'C', border = 'B')
    pdf.ln()

    pdf_sum_line(pdf, 'Datum:', date)
    pdf_sum_line(pdf, 'Antal transaktioner:', str(len(payments)))
    pdf_sum_line(pdf, 'Bruttobelopp:', gross_amount)
    pdf_sum_line(pdf, 'Avgift:', total_fee)
    pdf_sum_line(pdf, 'Nettobelopp:', net_amount)
    pdf_sum_line(pdf, 'Nytt saldo:', balance)

    # Generate one page for each payment
    for values in payments:
        pdf.add_page()

        for field, description in pdf_fields[language]:
            pdf_multi_line(pdf, description, values[field])

    # In Python3 fpdf 1.7.2 can only output latin-1
    with open(path, 'wt', encoding = 'latin-1') as f:
        print('wrote {}'.format(path))
        f.write(pdf.output(dest = 'S'))


def sum_amounts(payments, field):
    # Sum stripping commas so the last two digits are decimals
    total = sum([convert_numeric(p[field]) for p in payments])
    return '{},{:02d}'.format(int(total / 100), abs(total) % 100)

def convert_numeric(value):
    assert numeric_re.match(value), 'Invalid numeric value: {}'.format(value)
    return int(value.replace(',', ''))



def pdf_multi_line(pdf, description, value, align='L'):
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(60, 10, description)
    pdf.set_font('Arial', '', 14)
    pdf.multi_cell(0, 8, value, align=align)


def pdf_sum_line(pdf, description, value):
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(60, 10, description)
    pdf.set_font('Arial', '', 14)
    pdf.multi_cell(30, 8, value, align='R')


if __name__ == '__main__':
    main()
